const dayMs = 86400000
export const todayIso = () => new Date().toISOString().slice(0,10)
export const money = value => new Intl.NumberFormat('ar-IQ',{style:'currency',currency:'IQD',maximumFractionDigits:0}).format(Math.round(value))
export const compactMoney = value => {
  const a=Math.abs(value), s=value<0?'-':''
  if(a>=1e9)return `${s}${(a/1e9).toFixed(1)} مليار د.ع`
  if(a>=1e6)return `${s}${(a/1e6).toFixed(1)} مليون د.ع`
  if(a>=1e3)return `${s}${(a/1e3).toFixed(0)} ألف د.ع`
  return `${Math.round(value).toLocaleString('ar-IQ')} د.ع`
}
export const fullDate = iso => new Intl.DateTimeFormat('ar-IQ',{year:'numeric',month:'long',day:'numeric'}).format(new Date(`${iso}T12:00:00`))
export const shortDate = iso => new Intl.DateTimeFormat('ar-IQ',{month:'short',day:'numeric'}).format(new Date(`${iso}T12:00:00`))

function completedBalance(items){return items.filter(t=>t.status==='completed').reduce((s,t)=>s+(t.type==='income'?t.amount:-t.amount),0)}
function recentTotals(items,days=30){const cutoff=new Date(`${todayIso()}T12:00:00`).getTime()-days*dayMs;return items.filter(t=>t.status==='completed'&&new Date(`${t.date}T12:00:00`).getTime()>=cutoff).reduce((a,t)=>{a[t.type==='income'?'inflow':'outflow']+=t.amount;return a},{inflow:0,outflow:0})}
function forecast(items,days=14){let balance=completedBalance(items);const scheduled=items.filter(t=>t.status==='scheduled'),out=[];for(let i=0;i<=days;i++){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);const date=d.toISOString().slice(0,10),list=scheduled.filter(t=>t.date===date),inflow=list.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),outflow=list.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0);balance+=inflow-outflow;out.push({date,balance,inflow,outflow})}return out}
function detectRisks(items,points,currentBalance){const risks=[],negative=points.find(p=>p.balance<0);if(negative)risks.push({id:'negative-balance',severity:'high',title:'عجز سيولة متوقع',date:negative.date,amount:Math.abs(negative.balance),detail:`الرصيد المتوقع ينخفض تحت الصفر في ${fullDate(negative.date)}.`,evidence:[`العجز المتوقع: ${compactMoney(Math.abs(negative.balance))}`,`الرصيد الحالي: ${compactMoney(currentBalance)}`]});const expenses=items.filter(t=>t.status==='scheduled'&&t.type==='expense'),largest=[...expenses].sort((a,b)=>b.amount-a.amount)[0];if(largest&&largest.amount>Math.max(currentBalance*.35,750000))risks.push({id:'large-payment',severity:negative?'high':'medium',title:'دفعة كبيرة قادمة',date:largest.date,amount:largest.amount,detail:`${largest.description} ستسحب جزءًا كبيرًا من السيولة المتاحة.`,evidence:[`قيمة الدفعة: ${compactMoney(largest.amount)}`,`موعدها: ${fullDate(largest.date)}`]});const zi=items.filter(t=>t.status==='completed'&&t.type==='income'&&t.channel==='zaincash').reduce((s,t)=>s+t.amount,0),inc=items.filter(t=>t.status==='completed'&&t.type==='income').reduce((s,t)=>s+t.amount,0);if(inc>0&&zi/inc>.6)risks.push({id:'channel-concentration',severity:'low',title:'اعتماد مرتفع على قناة واحدة',detail:'جزء كبير من التحصيلات يأتي من ZainCash؛ راقب أي تأخر في التسوية.',evidence:[`نسبة دخل ZainCash: ${Math.round(zi/inc*100)}%`]});return risks}
function buildActions(items,risks,points){const a=[],negative=points.find(p=>p.balance<0),incoming=items.filter(t=>t.status==='scheduled'&&t.type==='income').sort((x,y)=>y.amount-x.amount)[0],large=items.filter(t=>t.status==='scheduled'&&t.type==='expense').sort((x,y)=>y.amount-x.amount)[0];if(negative){const gap=Math.ceil(Math.abs(negative.balance)*1.15/50000)*50000;a.push({id:'collect-gap',title:`حصّل ${compactMoney(gap)} قبل ${fullDate(negative.date)}`,detail:'هذا يضيف هامش أمان فوق العجز المتوقع بدل تغطيته بالحد الأدنى فقط.',impact:gap,urgency:'today'})}if(large)a.push({id:'negotiate-supplier',title:'فاوِض على تقسيم أكبر دفعة مورد',detail:`قسّم دفعة «${large.description}» إلى جزأين أو حرّك جزءًا منها عدة أيام إذا أمكن.`,impact:Math.round(large.amount*.4),urgency:'this-week'});if(incoming)a.push({id:'confirm-receivable',title:'ثبّت موعد أكبر تحصيل قادم',detail:`تأكد من تحصيل «${incoming.description}» في موعده لأن التوقع يعتمد عليه.`,impact:incoming.amount,urgency:'today'});if(!risks.some(r=>r.severity==='high'))a.push({id:'buffer',title:'كوّن احتياطي سيولة',detail:'احتفظ بجزء من التدفقات القادمة كحاجز بدل إعادة صرف كل الفائض مباشرة.',impact:250000,urgency:'monitor'});return a.slice(0,4)}
function explanation(balance,points,risks,actions){const n=points.find(p=>p.balance<0);if(n)return `نبض شايف أن عندك ${compactMoney(balance)} حاليًا، لكن حسب الحركات المجدولة الرصيد راح ينزل تحت الصفر في ${fullDate(n.date)} بحوالي ${compactMoney(Math.abs(n.balance))}. السبب مو ضعف المبيعات وحده؛ توقيت الدفعات الكبيرة أسرع من التحصيلات. أول أولوية الآن: ${actions[0]?.title||'زيادة هامش السيولة قبل موعد العجز'}.`;const min=points.reduce((a,b)=>a.balance<b.balance?a:b);return `السيولة تبدو مستقرة خلال فترة التوقع. أقل رصيد متوقع هو ${compactMoney(min.balance)} في ${fullDate(min.date)}. لا يوجد عجز مباشر، لكن نبض سيبقى يراقب الدفعات الكبيرة وتركيز التحصيلات.`}
export function runAgents(items){const valid=items.filter(t=>Number.isFinite(+t.amount)&&+t.amount>0&&/^\d{4}-\d{2}-\d{2}$/.test(t.date));const balance=completedBalance(valid),totals=recentTotals(valid),points=forecast(valid),runway=totals.outflow>0?Math.max(0,Math.floor(balance/(totals.outflow/30))):null,risks=detectRisks(valid,points,balance),actions=buildActions(valid,risks,points),exp=explanation(balance,points,risks,actions);return{generatedAt:new Date().toISOString(),currentBalance:balance,inflow30d:totals.inflow,outflow30d:totals.outflow,runwayDays:runway,forecast:points,risks,actions,explanation:exp,agentResults:[{agent:'observer',label:'وكيل المراقبة',status:'success',summary:`تمت قراءة ${valid.length} حركة صالحة من ${items.length}.`},{agent:'cashflow',label:'وكيل السيولة',status:points.some(p=>p.balance<0)?'warning':'success',summary:`الرصيد الحالي ${compactMoney(balance)}، والتوقع ممتد 14 يومًا.`},{agent:'risk',label:'وكيل المخاطر',status:risks.some(r=>r.severity==='high')?'warning':'success',summary:risks.length?`اكتشف ${risks.length} إشارة تحتاج الانتباه.`:'لا توجد مخاطر بارزة حاليًا.'},{agent:'reasoner',label:'وكيل التحليل',status:'success',summary:risks.find(r=>r.id==='large-payment')?.detail||(risks[0]?.detail||'التدفق الحالي متوازن ضمن البيانات المتاحة.')},{agent:'planner',label:'وكيل التخطيط',status:'success',summary:`بنى ${actions.length} إجراءات عملية مرتبة حسب الأولوية.`},{agent:'explainer',label:'وكيل الشرح',status:'success',summary:'حوّل التحليل إلى توصية مفهومة بدون مصطلحات محاسبية معقدة.'}]}}
export function runScenario(items,input){const c=items.map(t=>({...t}));if(input.extraCollection>0){const d=new Date();d.setDate(d.getDate()+2);c.push({id:'scenario-collection',date:d.toISOString().slice(0,10),amount:input.extraCollection,type:'income',category:'سيناريو',description:'تحصيل إضافي',channel:'other',status:'scheduled'})}if(input.reduceExpensesPct>0)c.forEach(t=>{if(t.status==='scheduled'&&t.type==='expense')t.amount*=1-input.reduceExpensesPct/100});if(input.delayLargeExpenseDays>0){const l=c.filter(t=>t.status==='scheduled'&&t.type==='expense').sort((a,b)=>b.amount-a.amount)[0];if(l){const d=new Date(`${l.date}T12:00:00`);d.setDate(d.getDate()+input.delayLargeExpenseDays);l.date=d.toISOString().slice(0,10)}}return runAgents(c)}
export function answerQuestion(q,report){q=q.trim().toLowerCase();if(!q)return 'اكتب سؤالك عن السيولة، العجز، المصروفات أو الإجراء الذي يجب تبدأ به.';const n=report.forecast.find(p=>p.balance<0);if(/عجز|ينفد|يخلص|سيولة/.test(q))return n?`نعم. وفق البيانات الحالية أول عجز متوقع في ${fullDate(n.date)} ويبلغ تقريبًا ${compactMoney(Math.abs(n.balance))}.`:'لا يظهر عجز خلال 14 يومًا.';if(/اسوي|أفعل|اولوية|أولوية|حل|شنو/.test(q))return report.actions[0]?`${report.actions[0].title}. ${report.actions[0].detail}`:'لا توجد خطوة طارئة الآن؛ راقب الدفعات والتحصيلات.';if(/صرف|مصاريف|مصروف/.test(q))return `إجمالي المصروفات المكتملة خلال آخر 30 يومًا هو ${compactMoney(report.outflow30d)}.`;if(/دخل|مبيعات|وارد/.test(q))return `إجمالي التدفقات الداخلة خلال آخر 30 يومًا هو ${compactMoney(report.inflow30d)}.`;if(/رصيد|عندي/.test(q))return `الرصيد المحسوب من الحركات المكتملة حاليًا هو ${compactMoney(report.currentBalance)}.`;return report.explanation}
